app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', [
	'as' => 'frontend',
	'uses' => 'HomeController@index'
]);

Route::get('change-password', [
	'as' => 'change-password.get',
	'uses' => 'Auth\PasswordController@changePassword'
]);

Route::post('change-password', [
	'as' => 'change-password.post',
	'uses' => 'Auth\PasswordController@updatePassword'
]);

Route::auth();

Route::get('/home', 'HomeController@index');
Route::put('users/{username}', [
	'as' => 'users.update',
	'uses' => 'UserController@update'
]);

Route::get('users-list', [
	'as' => 'users.index',
	'uses' => 'UserController@index'
]);

Route::get('users/approve', [
	'as' => 'users.approve',
	'uses' => 'UserController@approve'
]);

Route::get('users/{username}', [
	'as' => 'users.show',
	'uses' => 'UserController@show'
]);

Route::resource('stores', 'StoreController');
Route::get('stores-search', [
	'as' => 'stores-search',
	'uses' => 'StoreSearchController@index'
]);

Route::get('search/results', [
	'as' => 'search-results',
	'uses' => 'StoreSearchController@search'
]);

Route::resource('retailer-contacts', 'RetailerContactController');
Route::resource('products', 'ProductController');
Route::get('order', [
	'as' => 'orders.makeOrder',
	'uses' => 'ProductController@makeOrder'
]);

Route::get('orders/{id}/mark-complete', [
	'as' => 'orders.markComplete',
	'uses' => 'OrderController@markComplete'
]);

Route::get('orders/{id}/mark-pending', [
	'as' => 'orders.markPending',
	'uses' => 'OrderController@markPending'
]);

Route::resource('orders', 'OrderController');
Route::resource('order-payments', 'OrderPaymentController');
Route::resource('testomonials', 'TestomonialController');

Route::post('transactions/process', [
	'as' => 'transactions.process',
	'uses' => 'TransactionController@processTransaction'
]);

Route::get('payment/redirect', ['as' => 'paypal.redirect', 'uses' => 'TransactionController@processRedirect']);

Route::resource('faqs', 'FaqController');

Route::get('settings', 'SettingController@index');
Route::post('settings', [
	'as' => 'settings.store',
	'uses' => 'SettingController@store'
]);

/**
 * Frontend Routes
 */
Route::get('our-products', 'Frontends\ProductsController@index');
Route::get('our-products/{slug}', 'Frontends\ProductsController@show');
Route::get('faqs-list', 'Frontends\FaqController@index');
Route::post('mail/contact', [
	'as' => 'mail.contact',
	'uses' => 'Frontends\MailController@mailFromContactSection'
]);

/**
 * Temporary routes
 */
Route::get('about-us', function() {
	return view('pages.about');
});

Route::get('our-creation', function() {
	return view('pages.our-creation');
});

Route::get('product-analysis', function() {
	return view('pages.career');
});

Route::get('contact-us', function() {
	return view('pages.contact-us');
});

Route::get('pricing', 'Frontends\ProductsController@pricing');

Route::get('forms', function() {
	return view('pages.forms');
});

Route::get('shipping', function() {
	return view('pages.shipping');
});

Route::get('manage-retail', function() {
	return view('pages.manage-retail');
});

Route::get('processing-collection', function(){
	return view('pages.collection');
});

Route::get('quality-assurance', function() {
	return view('pages.quality-assurance');
});

app/Faq.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Faq extends Model
{
    use SoftDeletes;

	protected $fillable = [
		'title', 'description', 'slug'
	];
}

app/Testomonial.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Testomonial extends Model
{
    use SoftDeletes;

    protected $fillable = [
    	'name',	'title', 'description',	'company', 'company_website', 'image', 'designation'
    ];

    public function getPublishedAtAttribute($value)
    {
        return Carbon::parse($value);
    }

    public function getImageAttribute($value)
    {
    	if('' != trim($value)) {
    		return env('BASE_URL_FOR_FILE').$value;
    	}
    }
}

app/Http/Controllers/FaqController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests;
use App\Repositories\FaqRepository;
use App\Services\Validations\Validator;
use Illuminate\Http\Request;

class FaqController extends Controller
{
	/**
	 * [__construct description]
	 * @param FaqRepository $faqRepository [description]
	 */
    function __construct(FaqRepository $faqRepository, Request $request, Validator $validator)
    {
    	$this->faqRepository = $faqRepository;
    	$this->request = $request;
    	$this->validator = $validator;
    }

    public function index()
    {
    	$limit = $this->request->get('limit') ? $this->request->get('limit') : 10;
    	$faqs = $this->faqRepository->all($limit);
    	return view('admin.faqs.all', compact('faqs'));
    }

    public function create()
    {
    	return view('admin.faqs.create');
    }

    public function store()
    {
    	$params = $this->request->all();
    	$validate = $this->validator->isValid($params);

    	if(!$validate) {
    		return redirect()->back()
                ->withErrors($validator->getErrors())
                ->withInput();
    	}

    	$faq = $this->faqRepository->save($params);
    	return redirect()->route('faqs.index')->with("Faq title '". $faq->title ."' is added");
    }

    public function edit($slug)
    {
    	$faq = $this->faqRepository->findBySlug($slug);
    	return view('admin.faqs.edit', compact('faq'));
    }

    public function update($slug)
    {
    	$params = $this->request->all();
    	$validate = $this->validator->isValid($params);

    	if(!$validate) {
    		return redirect()->back()
                ->withErrors($validator->getErrors())
                ->withInput();
    	}

    	$faq = $this->faqRepository->update($slug, $params);
    	return redirect()->route('faqs.index')->with("Faq title '". $faq->title ."' is updated");
    }

    public function destroy($slug)
    {
    	$faq = $this->faqRepository->delete($slug);
    	return redirect()->route('faqs.index')->with("flash_message", "Faq title '". $faq->title ."' is deleted");
    }
}

app/Http/Controllers/Frontends/FaqController.php
<?php

namespace App\Http\Controllers\Frontends;

use App\Http\Controllers\Controller;
use App\Http\Requests;
use App\Repositories\FaqRepository;
use Illuminate\Http\Request;

class FaqController extends Controller
{
	/**
	 * [__construct description]
	 * @param FaqRepository $faqRepository [description]
	 */
    function __construct(FaqRepository $faqRepository, Request $request)
    {
    	$this->faqRepository = $faqRepository;
    	$this->request = $request;
    }

    public function index()
    {
    	$limit = $this->request->get('limit') ? $this->request->get('limit') : 10;
    	$faqs = $this->faqRepository->all($limit);
    	return view('frontend.faqs.all', compact('faqs'));
    }
}

resources/views/admin/faqs/all.blade.php
@extends('layouts.admin', ['pageBreadcrumb' => 'FAQs'])

@section('content')
<div class="table-section">
	<?php if (count($faqs) > 0): ?>
		<table class="table table-responsive">
			<thead>
				<tr style="border:none !important;">
					<th>Title</th>
					<th>Updated Date</th>
					<th>Action</th>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($faqs as $faq): ?>
					<tr>
						<td><?= $faq->title ?></td>
						<td><?= $faq->published_at->toFormattedDateString() ?></td>
						<td>
							<form style="display: inline-block" action="<?= route('faqs.destroy', $faq->slug) ?>" method="post">
		                        {!! csrf_field() !!}
		                        {{ method_field('DELETE') }}
		                        <button type="submit" class="btn btn-danger delete-store"><i class="fa fa-close"></i></button>
		                    </form>
		                    <a href="<?= route('faqs.edit', $faq->slug) ?>">
		                    	<button type="button" class="btn btn-info delete-store">
		                    		<i class="fa fa-pencil"></i>
		                    	</button>
		                    </a>
						</td>
					</tr>
				<?php endforeach; ?>
			</tbody>
		</table>
	<?php else: ?>
		<div class="alert alert-info">
			<p class="text-center">No FAQs found</p>
		</div>
	<?php endif ?>
</div>
<div class="container">
	{!! $faqs->links() !!}
</div>
@endsection

@section('footer')
<script type="text/javascript" src="<?= asset('js/bootbox.min.js') ?>"></script>
<script type="text/javascript">
    $(document).on('click', 'form', function(e) {
        var currentForm = $(this);
        e.preventDefault();
        bootbox.confirm('Are you sure?', function(result) {
            if(result) {
                currentForm.submit();
            }
        });
    });
</script>
@endsection

resources/views/admin/faqs/create.blade.php
@extends('layouts.admin', ['pageBreadcrumb' => 'FAQs'])

@section('content')
<div class="post-page">
	<form method="post" action="<?= route('faqs.store') ?>" enctype="multipart/form-data">
		{!! csrf_field() !!}
	  	<div class="form-group <?= $errors->has('title') ? 'has-error' : '' ?>">
		    <label for="title">Title</label>
		    <input type="text" class="form-control" id="title" placeholder="Title" name="title"
		    	value="<?= null !== old('title') ? old('title') : '' ?>">
		    <?php if ($errors->has('title')) : ?>
                <span class="help-block">
                    <strong>{{ $errors->first('title') }}</strong>
                </span>
            <?php endif; ?>
	  	</div>
	  	<div class="form-group <?= $errors->has('description') ? 'has-error' : '' ?>">
		    <label for="description">Description</label>
		    <textarea id="post-editor" class="post-editor form-control" name="description" rows="10"><?= null !== old('description') ? old('description') : '' ?></textarea>
		    <?php if ($errors->has('description')) : ?>
                <span class="help-block">
                    <strong>{{ $errors->first('description') }}</strong>
                </span>
            <?php endif; ?>
	  	</div>
	  	<button type="submit" class="btn btn-primary">Submit</button>
	</form>
</div>
@endsection

@section('footer')
<script src="{{ asset('/vendor/unisharp/laravel-ckeditor/ckeditor.js') }}"></script>
<script src="<?= asset('/vendor/unisharp/laravel-ckeditor/adapters/jquery.js') ?>"></script>
<script type="text/javascript">
	$('.post-editor').ckeditor();
</script>
@endsection

resources/views/admin/faqs/edit.blade.php
@extends('layouts.admin', ['pageBreadcrumb' => 'FAQs'])

@section('content')
<div class="post-page">
	<form method="post" action="<?= route('faqs.update', $faq->slug) ?>" enctype="multipart/form-data">
		{!! csrf_field() !!}
		{!! method_field('PUT') !!}
	  	<div class="form-group <?= $errors->has('title') ? 'has-error' : '' ?>">
		    <label for="title">Title</label>
		    <input type="text" class="form-control" id="title" placeholder="Title" name="title"
		    	value="<?= null !== old('title') ? old('title') : $faq->title ?>">
		    <?php if ($errors->has('title')) : ?>
                <span class="help-block">
                    <strong>{{ $errors->first('title') }}</strong>
                </span>
            <?php endif; ?>
	  	</div>
	  	<div class="form-group <?= $errors->has('description') ? 'has-error' : '' ?>">
		    <label for="description">Description</label>
		    <textarea id="post-editor" class="post-editor form-control" name="description" rows="10"><?= null !== old('description') ? old('description') : $faq->description ?></textarea>
		    <?php if ($errors->has('description')) : ?>
                <span class="help-block">
                    <strong>{{ $errors->first('description') }}</strong>
                </span>
            <?php endif; ?>
	  	</div>
	  	<button type="submit" class="btn btn-primary">Submit</button>
	</form>
</div>
@endsection

@section('footer')
<script src="{{ asset('/vendor/unisharp/laravel-ckeditor/ckeditor.js') }}"></script>
<script src="<?= asset('/vendor/unisharp/laravel-ckeditor/adapters/jquery.js') ?>"></script>
<script type="text/javascript">
	$('.post-editor').ckeditor();
</script>
@endsection