app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', [
	'as' => 'frontend',
	'uses' => 'HomeController@index'
]);

Route::get('change-password', [
	'as' => 'change-password.get',
	'uses' => 'Auth\PasswordController@changePassword'
]);

Route::post('change-password', [
	'as' => 'change-password.post',
	'uses' => 'Auth\PasswordController@updatePassword'
]);

Route::auth();

Route::get('/home', 'HomeController@index');
Route::put('users/{username}', [
	'as' => 'users.update',
	'uses' => 'UserController@update'
]);

Route::get('users-list', [
	'as' => 'users.index',
	'uses' => 'UserController@index'
]);

Route::get('users/approve', [
	'as' => 'users.approve',
	'uses' => 'UserController@approve'
]);

Route::get('users/{username}', [
	'as' => 'users.show',
	'uses' => 'UserController@show'
]);

Route::resource('stores', 'StoreController');
Route::get('stores-search', [
	'as' => 'stores-search',
	'uses' => 'StoreSearchController@index'
]);

Route::get('search/results', [
	'as' => 'search-results',
	'uses' => 'StoreSearchController@search'
]);

Route::resource('retailer-contacts', 'RetailerContactController');
Route::resource('products', 'ProductController');
Route::get('order', [
	'as' => 'orders.makeOrder',
	'uses' => 'ProductController@makeOrder'
]);

Route::get('orders/{id}/mark-complete', [
	'as' => 'orders.markComplete',
	'uses' => 'OrderController@markComplete'
]);

Route::get('orders/{id}/mark-pending', [
	'as' => 'orders.markPending',
	'uses' => 'OrderController@markPending'
]);

Route::resource('orders', 'OrderController');
Route::resource('order-payments', 'OrderPaymentController');
Route::resource('testomonials', 'TestomonialController');

Route::post('transactions/process', [
	'as' => 'transactions.process',
	'uses' => 'TransactionController@processTransaction'
]);

Route::get('payment/redirect', ['as' => 'paypal.redirect', 'uses' => 'TransactionController@processRedirect']);

Route::resource('faqs', 'FaqController');

Route::get('settings', 'SettingController@index');
Route::post('settings', [
	'as' => 'settings.store',
	'uses' => 'SettingController@store'
]);

/**
 * Frontend Routes
 */
Route::get('our-products', 'Frontends\ProductsController@index');
Route::get('our-products/{slug}', 'Frontends\ProductsController@show');
Route::get('faqs-list', 'Frontends\FaqController@index');
Route::post('mail/contact', [
	'as' => 'mail.contact',
	'uses' => 'Frontends\MailController@mailFromContactSection'
]);

/**
 * Temporary routes
 */
Route::get('about-us', function() {
	return view('pages.about');
});

Route::get('our-creation', function() {
	return view('pages.our-creation');
});

Route::get('product-analysis', function() {
	return view('pages.career');
});

Route::get('contact-us', function() {
	return view('pages.contact-us');
});

Route::get('pricing', 'Frontends\ProductsController@pricing');

Route::get('forms', function() {
	return view('pages.forms');
});

Route::get('shipping', function() {
	return view('pages.shipping');
});

Route::get('manage-retail', function() {
	return view('pages.manage-retail');
});

Route::get('processing-collection', function(){
	return view('pages.collection');
});

Route::get('quality-assurance', function() {
	return view('pages.quality-assurance');
});

app/RetailerContact.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class RetailerContact extends Model
{
    use SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'slug', 'designation', 'apt_ste', 'street_address', 'city', 'email', 'state_id', 'phone_number', 'fax_number', 'zip'
    ];

    /**
	 * Store belongs to State
	 */
    public function state()
    {
    	return $this->belongsTo('App\State');
    }
}

app/Http/Controllers/RetailerContactController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests;
use App\Services\RetailerContactService;
use App\Services\StateService;
use App\Services\Validations\Validator;
use Illuminate\Http\Request;

class RetailerContactController extends Controller
{
    /**
	 * Injecting dependencies
	 * 
	 * @param RetailerContactService $retailerContact
	 * @param Validator    $validate
	 * @param Request      $request
	 */
    function __construct(
    	RetailerContactService $retailerContactService,
    	StateService $stateService,
    	Validator $validate,
    	Request $request
    )
    {
    	$this->retailerContactService = $retailerContactService;
    	$this->stateService = $stateService;
    	$this->validate = $validate;
    	$this->request = $request;
    }

    public function index()
    {
    	$limit = null !== $this->request->get('limit') ? $this->request->get('limit') : 20;
    	$retailerContacts = $this->retailerContactService->all($limit);
    	return view('retailer-contacts.all', compact('retailerContacts'));
    }

    public function create()
	{
		$states = $this->stateService->allWithoutPagination();
		return view('retailer-contacts.create', compact('states'));
	}

	public function store()
	{
		$params = $this->request->all();
    	$validate = $this->validate->isValid($params);

    	if(!$validate) {
    		return redirect()->back()
    			->withErrors($this->validate->getErrors())
    			->withInput();
    	}

    	$retailerContact = $this->retailerContactService->save($params);

    	return redirect()->route('retailer-contacts.index')
                ->with('flash_message', $retailerContact->name. ' is created.');
	}

    public function edit($slug)
    {
        $retailerContact = $this->retailerContactService->get($slug);
        $states = $this->stateService->allWithoutPagination();
        return view('retailer-contacts.edit', compact('states', 'retailerContact'));
    }

    public function update($slug)
    {
        $params = $this->request->all();
        $validate = $this->validate->isValid($params);

        if(!$validate) {
            return redirect()->back()
                ->with('flash_message', 'You got some errors in the form.')
                ->withErrors($this->validate->getErrors())
                ->withInput();
        }

        $retailerContact = $this->retailerContactService->update($slug, $params);
        return redirect()->route('retailer-contacts.index')
                ->with('flash_message', $retailerContact->name. ' is updated.');
    }

    public function destroy($slug)
    {
        $this->retailerContactService->delete($slug);
        return redirect()->route('retailer-contacts.index')
                ->with('flash_message', 'Contact is deleted.');
    }
}

resources/views/retailer-contacts/all.blade.php
@extends('layouts.app', ['bodyClass' => 'find-us'])

@section('content')
<!-- store section start -->
<section class="store-section"> 
  <div class="container">
      <strong>Contact</strong>
      <div class="ad-your-store">
        <a href="<?= route('retailer-contacts.create') ?>" title="">Add Your New Contact +</a>
      </div>
      <div class="row">
        <div class="store-wraper mange-store">
        	<?php foreach ($retailerContacts as $retailerContact): ?>
        		<div class="col-sm-6  col-md-6">
		            <div class="store-content">
		               <h4><?= $retailerContact->name ?></h4>
		               <p>
		                  	Phone number: <?= $retailerContact->phone_number ?>
		                  	Designation: <?= $retailerContact->designation ?><br>
							Address:<?= $retailerContact->street_address ?>, <?= $retailerContact->city ?><br>
							Email: <?= $retailerContact->email ?><br>
							Fax: <?= $retailerContact->fax_number ?><br>
		                </p>  
		                <form action="<?= route('retailer-contacts.destroy', $retailerContact->slug) ?>" method="post">
                        {!! csrf_field() !!}
                        {{ method_field('DELETE') }}
                        <button type="submit" class="btn btn-warning delete-store">Delete</button>
                    </form>
		                <a href="<?= route('retailer-contacts.edit', $retailerContact->slug) ?>" type="btn" class="btn btn-primary" title="">Edit</a>
		            </div> 
		          </div>
        	<?php endforeach ?>
        	{!! $retailerContacts->links() !!}
        </div>
      </div>
   </div>   
</section>
<!-- store section end  -->

<!-- are you sure section start  -->
<section class="are-your-sure">
  <div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Are Your Sure</h4>
        </div>
        <div class="modal-body">
          <button type="button" class="btn btn-success btn-lg">Yes</button>
          <button type="button" class="btn btn-warning btn-lg">No</button>
        </div>
      </div>

    </div>
  </div>
</section>
<!-- are you sure section end  -->
@endsection

@section('footer')
<script type="text/javascript" src="<?= asset('js/bootbox.min.js') ?>"></script>
<script type="text/javascript">
    $(document).on('click', 'form', function(e) {
        var currentForm = $(this);
        e.preventDefault();
        bootbox.confirm('Are you sure?', function(result) {
            if(result) {
                currentForm.submit();
            }
        });
    });
</script>
@endsection

resources/views/retailer-contacts/create.blade.php
@extends('layouts.app', ['bodyClass' => 'find-us'])

@section('content')
<!-- edit section start -->
<section class="join-us">
    <strong>ADD/MANAGE YOUR STORE(S)</strong>
    <div class="join-us-form">
        <div class="container">
            <div class="row"> 
                <div class="join-us-form-wrapper">
                    <form action="<?= route('retailer-contacts.store') ?>" method="post">
                    	{!! csrf_field() !!}
                        <div class="form-group col-lg-6 col-sm-6">
                            <input type="text" name="name" class="form-control" placeholder="Name">
                        </div>
                        <div class="form-group col-lg-6 col-sm-6">
                          	<input type="text" name="designation" class="form-control"  placeholder="Title/Designation">
                        </div>
                        <div class="form-group col-lg-6 col-sm-6">
                          	<input type="text" name="apt_ste" class="form-control"  placeholder="APT/Suite">
                        </div>
                        <div class="form-group col-lg-6 col-sm-6">
                          	<input type="text" name="street_address" class="form-control"  placeholder="Street Address">
                        </div>
                        <div class="form-group col-lg-6 col-sm-6">
                          	<input type="text" name="city" class="form-control"  placeholder="City">
                        </div>
                        <div class="form-group col-lg-6 col-sm-6">
                          	<input type="text" name="phone_number" class="form-control"  placeholder="phone_number">
                        </div>
                        <div class="form-group col-lg-6 col-sm-6">
                          	<input type="text" name="email" class="form-control"  placeholder="Email">
                        </div>
                        <div class="form-group col-lg-6 col-sm-6">
                          	<input type="text" name="fax_number" class="form-control"  placeholder="fax">
                        </div>
                        <div class="form-group col-lg-6 col-sm-6">
                          	<input type="text" name="zip" class="form-control"  placeholder="Zip">
                        </div>
                        <div class="form-group col-lg-6 col-sm-6">
                          	<select name="state_id">
                          		<?php foreach ($states as $state): ?>
                          			<option value="<?= $state->id ?>"><?= $state->name ?></option>
                          		<?php endforeach ?>
                          	</select>
                        </div>
                        <div class="form-group col-lg-12 col-sm-12">
                          	<input type="checkbox" id="c1" name="cc" />
                          	<label for="c1">I have read the Privacy Policy and Web Usage Agreement</label>
                        </div>
                        <button type="submit" class="btn btn-primary btn-lg">Submit</button>
                    </form>
                </div>
            </div> 
        </div>
    </div>
</section>
<!-- edit section end  -->

@endsection

resources/views/retailer-contacts/edit.blade.php
@extends('layouts.app', ['bodyClass' => 'find-us'])

@section('content')

<!-- edit section start -->
<section class="join-us">
    <strong>ADD/MANAGE YOUR CONTACT(S)</strong>
    <div class="join-us-form">
        <div class="container">
            <div class="row"> 
                <div class="join-us-form-wrapper">
                    <form action="<?= route('retailer-contacts.update', $retailerContact->slug) ?>" method="post">
                    	{!! csrf_field() !!}
                    	{{ method_field('PUT') }}
                        <div class="form-group col-lg-6 col-sm-6">
                            <input type="text" name="name" class="form-control" placeholder="Store Name" value="<?= (null !== old('name') ? old('name') : $retailerContact->name) ?>">
                        </div>
                        <div class="form-group col-lg-6 col-sm-6">
                          	<input type="text" name="designation" class="form-control"  placeholder="designation" value="<?= (null !== old('designation') ? old('designation') : $retailerContact->designation) ?>">
                        </div>
                        <div class="form-group col-lg-6 col-sm-6">
                          	<input type="text" name="apt_ste" class="form-control"  placeholder="apt_ste" value="<?= (null !== old('apt_ste') ? old('apt_ste') : $retailerContact->apt_ste) ?>">
                        </div>
                        <div class="form-group col-lg-6 col-sm-6">
                          	<input type="text" name="street_address" class="form-control"  placeholder="Street Address" value="<?= (null !== old('street_address') ? old('street)address') : $retailerContact->street_address) ?>">
                        </div>
                        <div class="form-group col-lg-6 col-sm-6">
                          	<input type="text" name="city" class="form-control"  placeholder="City" value="<?= (null !== old('city') ? old('city') : $retailerContact->city) ?>">
                        </div>
                        <div class="form-group col-lg-6 col-sm-6">
                          	<input type="text" name="phone_number" class="form-control"  placeholder="phone_number" value="<?= (null !== old('phone_number') ? old('phone_number') : $retailerContact->phone_number) ?>">
                        </div>
                        <div class="form-group col-lg-6 col-sm-6">
                          	<input type="text" name="email" class="form-control"  placeholder="Email" value="<?= (null !== old('email') ? old('email') : $retailerContact->email) ?>">
                        </div>
                        <div class="form-group col-lg-6 col-sm-6">
                          	<input type="text" name="fax_number" class="form-control"  placeholder="fax" value="<?= (null !== old('fax_number') ? old('fax_number') : $retailerContact->fax_number) ?>">
                        </div>
                        <div class="form-group col-lg-6 col-sm-6">
                          	<input type="text" name="zip" class="form-control"  placeholder="Zip" value="<?= (null !== old('zip') ? old('zip') : $retailerContact->zip) ?>">
                        </div>
                        <div class="form-group col-lg-6 col-sm-6">
                          	<select name="state_id">
                          		<?php foreach ($states as $state): ?>
                          			<option value="<?= $state->id ?>" <?= (null !== old('state_id')) ? 'selected' : ($state->id == $retailerContact->state_id) ? 'selected' : '' ?>><?= $state->name ?></option>
                          		<?php endforeach ?>
                          	</select>
                        </div>
                        <div class="form-group col-lg-12 col-sm-12">
                          	<input type="checkbox" id="c1" name="cc" <?= (null !== old('city')) ? 'checked' : ''; ?> />
                          	<label for="c1">I have read the Privacy Policy and Web Usage Agreement</label>
                        </div>
                        <button type="submit" class="btn btn-primary btn-lg">Submit</button>
                    </form>
                </div>
            </div> 
        </div>
    </div>
</section>
<!-- edit section end  -->

@endsection