app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', [
	'as' => 'frontend',
	'uses' => 'HomeController@index'
]);

Route::get('change-password', [
	'as' => 'change-password.get',
	'uses' => 'Auth\PasswordController@changePassword'
]);

Route::post('change-password', [
	'as' => 'change-password.post',
	'uses' => 'Auth\PasswordController@updatePassword'
]);

Route::auth();

Route::get('/home', 'HomeController@index');
Route::put('users/{username}', [
	'as' => 'users.update',
	'uses' => 'UserController@update'
]);

Route::get('users-list', [
	'as' => 'users.index',
	'uses' => 'UserController@index'
]);

Route::get('users/approve', [
	'as' => 'users.approve',
	'uses' => 'UserController@approve'
]);

Route::get('users/{username}', [
	'as' => 'users.show',
	'uses' => 'UserController@show'
]);

Route::resource('stores', 'StoreController');
Route::get('stores-search', [
	'as' => 'stores-search',
	'uses' => 'StoreSearchController@index'
]);

Route::get('search/results', [
	'as' => 'search-results',
	'uses' => 'StoreSearchController@search'
]);

Route::resource('retailer-contacts', 'RetailerContactController');
Route::resource('products', 'ProductController');
Route::get('order', [
	'as' => 'orders.makeOrder',
	'uses' => 'ProductController@makeOrder'
]);

Route::get('orders/{id}/mark-complete', [
	'as' => 'orders.markComplete',
	'uses' => 'OrderController@markComplete'
]);

Route::get('orders/{id}/mark-pending', [
	'as' => 'orders.markPending',
	'uses' => 'OrderController@markPending'
]);

Route::resource('orders', 'OrderController');
Route::resource('order-payments', 'OrderPaymentController');
Route::resource('testomonials', 'TestomonialController');

Route::post('transactions/process', [
	'as' => 'transactions.process',
	'uses' => 'TransactionController@processTransaction'
]);

Route::get('payment/redirect', ['as' => 'paypal.redirect', 'uses' => 'TransactionController@processRedirect']);

Route::resource('faqs', 'FaqController');

Route::get('settings', 'SettingController@index');
Route::post('settings', [
	'as' => 'settings.store',
	'uses' => 'SettingController@store'
]);

/**
 * Frontend Routes
 */
Route::get('our-products', 'Frontends\ProductsController@index');
Route::get('our-products/{slug}', 'Frontends\ProductsController@show');
Route::get('faqs-list', 'Frontends\FaqController@index');
Route::post('mail/contact', [
	'as' => 'mail.contact',
	'uses' => 'Frontends\MailController@mailFromContactSection'
]);

/**
 * Temporary routes
 */
Route::get('about-us', function() {
	return view('pages.about');
});

Route::get('our-creation', function() {
	return view('pages.our-creation');
});

Route::get('product-analysis', function() {
	return view('pages.career');
});

Route::get('contact-us', function() {
	return view('pages.contact-us');
});

Route::get('pricing', 'Frontends\ProductsController@pricing');

Route::get('forms', function() {
	return view('pages.forms');
});

Route::get('shipping', function() {
	return view('pages.shipping');
});

Route::get('manage-retail', function() {
	return view('pages.manage-retail');
});

Route::get('processing-collection', function(){
	return view('pages.collection');
});

Route::get('quality-assurance', function() {
	return view('pages.quality-assurance');
});

app/Testomonial.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Testomonial extends Model
{
    use SoftDeletes;

    protected $fillable = [
    	'name',	'title', 'description',	'company', 'company_website', 'image', 'designation'
    ];

    public function getPublishedAtAttribute($value)
    {
        return Carbon::parse($value);
    }

    public function getImageAttribute($value)
    {
    	if('' != trim($value)) {
    		return env('BASE_URL_FOR_FILE').$value;
    	}
    }
}

app/Http/Controllers/TestomonialController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests;
use App\Services\TestomonialService;
use App\Services\Validations\Validator;
use Illuminate\Http\Request;

class TestomonialController extends Controller
{
	/**
	 * Injecting dependencies
	 * 
	 * @param TestomonialService $testomonialService
	 * @param Validator          $validator
	 */
    function __construct(TestomonialService $testomonialService, Validator $validator, Request $request)
    {
    	$this->testomonialService = $testomonialService;
    	$this->validator = $validator;
    	$this->request = $request;
    }

    public function index()
    {
    	$limit = $this->request->get('limit') ? $this->request->get('limit') : 10;
    	$testomonials = $this->testomonialService->all($limit);
        return view('admin.testomonials.all', compact('testomonials'));
    }

    public function create()
    {
        return view('admin.testomonials.create');
    }

    public function store()
    {
    	$params = $this->request->all();
    	$validate = $this->validator->isValid($params);

    	if(!$validate) {
    		return redirect()->back()
                ->withErrors($validator->getErrors())
                ->withInput();
    	}

    	$this->testomonialService->save($params);
        return redirect()->route('testomonials.index')->with('flash_message', $params['title'].' testomonial is added.');
    }

    public function edit($slug)
    {
        $testomonial = $this->testomonialService->get($slug);
        return view('admin.testomonials.edit', compact('testomonial'));
    }

    public function update($id)
    {
    	$params = $this->request->all();
    	$validate = $this->validator->mergeWithExistingRules('image', 'image')->isValid($params);

    	if(!$validate) {
    		return redirect()->back()
                ->withErrors($validator->getErrors())
                ->withInput();
    	}

    	$this->testomonialService->update($id, $params);
        return redirect()->route('testomonials.index')
            ->with('flash_message', $params['title'].' testomonial is updated.');
    }

    public function destroy($id)
    {
    	$this->testomonialService->delete($id);
        return redirect()->route('testomonials.index')
            ->with('flash_message', 'Testomonial is deleted.');
    }
}

resources/views/admin/testomonials/all.blade.php
@extends('layouts.admin', ['pageBreadcrumb' => 'Products'])

@section('content')
<div class="table-section">
	<table class="table table-responsive">
		<thead>
			<tr style="border:none !important;">
				<th>Image</th>
				<th>Name</th>
				<th>Title</th>
				<th>Publish Date</th>
				<th>Action</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach ($testomonials as $testomonial): ?>
				<tr>
					<td><img width="100" src="<?= $testomonial->image ?>" /></td>
					<td><?= $testomonial->name ?></td>
					<td><?= $testomonial->title ?></td>
					<td><?= $testomonial->published_at->toFormattedDateString() ?></td>
					<td>
						<form style="display: inline-block" action="<?= route('testomonials.destroy', $testomonial->slug) ?>" method="post">
	                        {!! csrf_field() !!}
	                        {{ method_field('DELETE') }}
	                        <button type="submit" class="btn btn-danger delete-store"><i class="fa fa-close"></i></button>
	                    </form>
	                    <a href="<?= route('testomonials.edit', $testomonial->slug) ?>">
	                    	<button type="button" class="btn btn-info delete-store">
	                    		<i class="fa fa-pencil"></i>
	                    	</button>
	                    </a>
					</td>
				</tr>
			<?php endforeach; ?>
		</tbody>
	</table>
</div>
<div class="container">
	{!! $testomonials->links() !!}
</div>
@endsection

@section('footer')
<script type="text/javascript" src="<?= asset('js/bootbox.min.js') ?>"></script>
<script type="text/javascript">
    $(document).on('click', 'form', function(e) {
        var currentForm = $(this);
        e.preventDefault();
        bootbox.confirm('Are you sure?', function(result) {
            if(result) {
                currentForm.submit();
            }
        });
    });
</script>
@endsection

resources/views/admin/testomonials/create.blade.php
@extends('layouts.admin', ['pageBreadcrumb' => 'Products'])

@section('header')
<link rel="stylesheet" type="text/css" href="<?= asset('js/jquery-ui/jquery-ui.css') ?>">
@endsection

@section('content')
<div class="post-page">
	<form method="post" action="<?= route('testomonials.store') ?>" enctype="multipart/form-data">
		{!! csrf_field() !!}
	  	<div class="form-group <?= $errors->has('title') ? 'has-error' : '' ?>">
		    <label for="title">Title</label>
		    <input type="text" class="form-control" id="title" placeholder="Title" name="title"
		    	value="<?= null !== old('title') ? old('title') : '' ?>">
		    <?php if ($errors->has('title')) : ?>
                <span class="help-block">
                    <strong>{{ $errors->first('title') }}</strong>
                </span>
            <?php endif; ?>
	  	</div>
	  	<div class="form-group <?= $errors->has('description') ? 'has-error' : '' ?>">
		    <label for="description">Description</label>
		    <textarea id="post-editor" class="post-editor form-control" name="description" rows="10"><?= null !== old('description') ? old('description') : '' ?></textarea>
		    <?php if ($errors->has('description')) : ?>
                <span class="help-block">
                    <strong>{{ $errors->first('description') }}</strong>
                </span>
            <?php endif; ?>
	  	</div>
	
		<div class="form-group <?= $errors->has('name') ? 'has-error' : '' ?>">
		    <label for="upc">Name</label>
		    <input type="text" class="form-control" id="upc" placeholder="Name" name="name"
		    	value="<?= null !== old('name') ? old('name') : '' ?>">
		    <?php if ($errors->has('name')) : ?>
                <span class="help-block">
                    <strong>{{ $errors->first('name') }}</strong>
                </span>
            <?php endif; ?>
	  	</div>

	  	<div class="form-group <?= $errors->has('image') ? 'has-error' : '' ?>">
		    <label for="image">Image</label>
		    <input type="file" class="form-control" name="image" id="image">
		    <?php if ($errors->has('image')): ?>
		    	<span class="help-block">
                    <p>{{ $errors->first('image') }}</p>
                </span>
		    <?php endif ?>
	  	</div>

	  	<div class="form-group <?= $errors->has('designation') ? 'has-error' : '' ?>">
		    <label for="upc">Designation</label>
		    <input type="text" class="form-control" id="upc" placeholder="Name" name="designation"
		    	value="<?= null !== old('designation') ? old('designation') : '' ?>">
		    <?php if ($errors->has('designation')) : ?>
                <span class="help-block">
                    <strong>{{ $errors->first('designation') }}</strong>
                </span>
            <?php endif; ?>
	  	</div>

	  	<div class="form-group <?= $errors->has('company') ? 'has-error' : '' ?>">
		    <label for="company">Company</label>
		    <input type="text" class="form-control" id="company" placeholder="Regular Price" name="company"
		    	value="<?= null !== old('company') ? old('company') : '' ?>">
		    <?php if ($errors->has('company')) : ?>
                <span class="help-block">
                    <strong>{{ $errors->first('company') }}</strong>
                </span>
            <?php endif; ?>
	  	</div>

	  	<div class="form-group <?= $errors->has('company_website') ? 'has-error' : '' ?>">
		    <label for="company_website">Company Website</label>
		    <input type="text" class="form-control" id="company_website" placeholder="Discount Price" name="company_website"
		    	value="<?= null !== old('company_website') ? old('company_website') : '' ?>">
		    <?php if ($errors->has('company_website')) : ?>
                <span class="help-block">
                    <strong>{{ $errors->first('company_website') }}</strong>
                </span>
            <?php endif; ?>
	  	</div>

	  	<div class="form-group <?= $errors->has('published_at') ? 'has-error' : '' ?>">
		    <label for="published_at">Published Date</label>
		    <input type="text" class="datepicker form-control" name="published_at">
		    <?php if ($errors->has('published_at')) : ?>
                <span class="help-block">
                    <strong>{{ $errors->first('published_at') }}</strong>
                </span>
            <?php endif; ?>
	  	</div>
	  	<button type="submit" class="btn btn-primary">Submit</button>
	</form>
</div>
@endsection

@section('footer')
<script src="{{ asset('ckeditor/ckeditor.js') }}"></script>
<script src="<?= asset('/vendor/unisharp/laravel-ckeditor/adapters/jquery.js') ?>"></script>
<script type="text/javascript" src="<?= asset('js/jquery-ui/jquery-ui.js'); ?>"></script>
<script type="text/javascript">
	$(".datepicker").datepicker();
	// $('.post-editor').ckeditor();
</script>
@endsection

resources/views/admin/testomonials/edit.blade.php
@extends('layouts.admin', ['pageBreadcrumb' => 'Products'])

@section('header')
<link rel="stylesheet" type="text/css" href="<?= asset('js/jquery-ui/jquery-ui.css') ?>">
@endsection

@section('content')
<div class="post-page">
	<form method="post" action="<?= route('testomonials.update', $testomonial->slug) ?>" enctype="multipart/form-data">
		{!! csrf_field() !!}
		{!! method_field('PUT') !!}
	  	<div class="form-group <?= $errors->has('title') ? 'has-error' : '' ?>">
		    <label for="title">Title</label>
		    <input type="text" class="form-control" id="title" placeholder="Title" name="title"
		    	value="<?= null !== old('title') ? old('title') : $testomonial->title ?>">
		    <?php if ($errors->has('title')) : ?>
                <span class="help-block">
                    <strong>{{ $errors->first('title') }}</strong>
                </span>
            <?php endif; ?>
	  	</div>
	  	<div class="form-group <?= $errors->has('description') ? 'has-error' : '' ?>">
		    <label for="description">Description</label>
		    <textarea id="post-editor" class="post-editor form-control" name="description" rows="10"><?= null !== old('description') ? old('description') : $testomonial->description ?></textarea>
		    <?php if ($errors->has('description')) : ?>
                <span class="help-block">
                    <strong>{{ $errors->first('description') }}</strong>
                </span>
            <?php endif; ?>
	  	</div>
	
		<div class="form-group <?= $errors->has('name') ? 'has-error' : '' ?>">
		    <label for="upc">Name</label>
		    <input type="text" class="form-control" id="upc" placeholder="Name" name="name"
		    	value="<?= null !== old('name') ? old('name') : $testomonial->name ?>">
		    <?php if ($errors->has('name')) : ?>
                <span class="help-block">
                    <strong>{{ $errors->first('name') }}</strong>
                </span>
            <?php endif; ?>
	  	</div>

	  	<div class="form-group <?= $errors->has('image') ? 'has-error' : '' ?>">
		    <label for="image">Image</label>
		    <input type="file" class="form-control" name="image" id="image">
		    <?php if ($errors->has('image')): ?>
		    	<span class="help-block">
                    <p>{{ $errors->first('image') }}</p>
                </span>
		    <?php endif ?>
	  	</div>

	  	<div class="form-group <?= $errors->has('designation') ? 'has-error' : '' ?>">
		    <label for="upc">Designation</label>
		    <input type="text" class="form-control" id="upc" placeholder="Name" name="designation"
		    	value="<?= null !== old('designation') ? old('designation') : $testomonial->designation ?>">
		    <?php if ($errors->has('designation')) : ?>
                <span class="help-block">
                    <strong>{{ $errors->first('designation') }}</strong>
                </span>
            <?php endif; ?>
	  	</div>

	  	<div class="form-group <?= $errors->has('company') ? 'has-error' : '' ?>">
		    <label for="company">Company</label>
		    <input type="text" class="form-control" id="company" placeholder="Regular Price" name="company"
		    	value="<?= null !== old('company') ? old('company') : $testomonial->company ?>">
		    <?php if ($errors->has('company')) : ?>
                <span class="help-block">
                    <strong>{{ $errors->first('company') }}</strong>
                </span>
            <?php endif; ?>
	  	</div>

	  	<div class="form-group <?= $errors->has('company_website') ? 'has-error' : '' ?>">
		    <label for="company_website">Company Website</label>
		    <input type="text" class="form-control" id="company_website" placeholder="Discount Price" name="company_website"
		    	value="<?= null !== old('company_website') ? old('company_website') : $testomonial->company_website ?>">
		    <?php if ($errors->has('company_website')) : ?>
                <span class="help-block">
                    <strong>{{ $errors->first('company_website') }}</strong>
                </span>
            <?php endif; ?>
	  	</div>

	  	<div class="form-group <?= $errors->has('published_at') ? 'has-error' : '' ?>">
		    <label for="published_at">Published Date</label>
		    <input type="text" class="datepicker form-control" name="published_at" value="<?= $testomonial->published_at->format('m/d/Y') ?>">
		    <?php if ($errors->has('published_at')) : ?>
                <span class="help-block">
                    <strong>{{ $errors->first('published_at') }}</strong>
                </span>
            <?php endif; ?>
	  	</div>
	  	<button type="submit" class="btn btn-primary">Submit</button>
	</form>
</div>
@endsection

@section('footer')
<script src="{{ asset('ckeditor/ckeditor.js') }}"></script>
<script src="<?= asset('/vendor/unisharp/laravel-ckeditor/adapters/jquery.js') ?>"></script>
<script type="text/javascript" src="<?= asset('js/jquery-ui/jquery-ui.js'); ?>"></script>
<script type="text/javascript">
	$(".datepicker").datepicker();
	// $('.post-editor').ckeditor();
</script>
@endsection